version: "3.5"

services:
  integration_base:
    build:
      context: ./
      dockerfile: ./Dockerfile.dev.base
    image: hyperdrive_gateway_integration_base:dev
  seeder: 
    image: hyperdrive_gateway_integration_base:dev
    container_name: dev_seeder
    command: ['node', 'dev-seeder/index.js']
    depends_on:
      - integration_base
    networks:
      - hyperdrive_gateway
  gateway:
    build:
      context: ./hyperdrive-gateway-server
      dockerfile: ./Dockerfile.dev
    image: hyperdrive_gateway_server:dev
    container_name: gateway_server
    networks:
      - hyperdrive_gateway
    ports:
      - "8080:8080"
    volumes:
      - /app/node_modules
      - ./hyperdrive-gateway-server:/app
      - ./dev-certs:/dev-certs
      - core_storage:/core_storage
    environment:
      CORE_STORAGE: /core_storage
      NODE_ENV: development
      PORT: '8080'
      PUBLIC_ASSETS_DIRECTORY: ''
      SSL_KEY: /dev-certs/local.computer.key
      SSL_CERT: /dev-certs/local.computer.crt
  ui:
    build:
      context: ./hyperdrive-gateway-ui
      dockerfile: ./Dockerfile.dev
    image: hyperdrive_gateway_ui:dev
    container_name: gateway_ui
    ports:
      - "8081:8081"
    volumes:
      - /app/node_modules
      - ./hyperdrive-gateway-ui:/app
      - ./dev-certs:/dev-certs
    environment:
      NODE_ENV: development
      SNOWPATH_PUBLIC_APP_NAME: 'Hyperdrive Gateway'
      SNOWPACK_PUBLIC_GATEWAY_HOST: local.computer:8080

networks:
  hyperdrive_gateway:
    name: hyperdrive_gateway_net

volumes:
  core_storage:

