version: "3.5"

services:
  integration_base:
    build:
      context: ./
      dockerfile: ./Dockerfile.dev.base
    image: hyperdrive_gateway_integration_base:dev
  seeder: 
    image: hyperdrive_gateway_integration_base:dev
    container_name: hyperdrive_gateway_seeder
    command: ['node', 'seeder/index.js']
    depends_on:
      - integration_base
    networks:
      - hyperspace_gateway
  gateway:
    build:
      context: ./hyperdrive-gateway
      dockerfile: ./Dockerfile.dev
    image: hyperdrive_gateway:dev
    container_name: hyperdrive_gateway
    networks:
      - hyperspace_gateway
    ports:
      - "8080:443"
    volumes:
      - /app/node_modules
      - ../hyperdrive-gateway:/app
      - hyperspace_storage:/hyperspace_storage
      - ./dev-certs:/dev-certs
    environment:
      APP_NAME: 'Hyperdrive Gateway'
      HYPERSPACE_STORAGE: /hyperspace_storage
      NODE_ENV: development
      PORT: '443'      
      SSL_KEY: /dev-certs/local.computer.key
      SSL_CERT: /dev-certs/local.computer.crt
  ui:
    build:
      context: ./hyperdrive-gateway-ui
      dockerfile: ./Dockerfile.dev
    image: hyperdrive_gateway_ui:dev
    container_name: hyperdrive_gateway_ui
    ports:
      - "8081:8080"
    volumes:
      - /app/node_modules
      - ../hyperdrive-gateway-ui:/app
      - ./dev-certs:/dev-certs
    environment:
      NODE_ENV: development
      SNOWPATH_PUBLIC_APP_NAME: 'Hyperdrive Gateway'
      SNOWPACK_PUBLIC_GATEWAY_HOST: local.computer:8080

networks:
  hyperspace_gateway:
    name: hyperspace_gateway_net

volumes:
  hyperspace_storage:

